---
title: "{{< var course.short >}} - Additional Resources and Course Policies"
---

## Course Resources

There are no required textbooks for this course.
Supplemental readings and suggested practice will be
assigned from the following readily-available resources: 

- [*Mathematics for Machine Learning* by Diesenroth, Faisal, and Ong (DFO)](http://mml-book.github.io)
- [*Convex Optimization* by Boyd and Vandenberghe (BV)](https://web.stanford.edu/~boyd/cvxbook/)
- [*Introduction to Statistical Learning* by James, 
  Witten, Hastie, and Tibshirani (ISL)](https://www.statlearning.com/)
- [*Elements of Statistical Learning* by Hastie Tibshirani,
  and Freedman (ESL)](https://hastie.su.domains/ElemStatLearn/)
- [*Statistical Learning with Sparsity* by Hastie, Tibshirani, and
   Wainwright (SLS)](https://hastie.su.domains/StatLearnSparsity/)
- [*Pattern Recognition and Machine Learning* by Bishop 
  (PRML)](https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/)
- [*Probabilistic Machine Learning: An Introduction* by Murphy (PML-1)](https://probml.github.io/pml-book/book1.html)
- [*Probabilistic Machine Learning: Advanced Topics* by Murphy (PML-2)](https://probml.github.io/pml-book/book2.html)
- [*Gaussian Processes for Machine Learning* by Rasmussen and Williams (GPML)](https://doi.org/10.7551/mitpress/3206.001.0001)
- [*Reinforcement Learning* by Sutton and Hutto (RL)](http://www.incompleteideas.net/book/the-book-2nd.html)
- [*Boosting: Foundations and Algorithms* by Schapire and Freund (SF)](https://doi.org/10.7551/mitpress/8291.001.0001)
- [*Foundations of Machine Learning* by Mohri, Rostamizadeh, and Talwalkar (FML)](https://cs.nyu.edu/~mohri/mlbook/)
- [*Understanding Machine Learning: From Theory to Algorithms* by Shalev-Shwartz and Ben-David (UML)](https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/)
- [*Patterns, Predictions, and Actions* by Hardt and Recht (HR)](https://mlstory.org)
- [*Fairness and Machine Learning* by Barocas, Hardt, and Narayanan (BHN)](https://fairmlbook.org/)
- [*Learning Theory from First Principles* by Bach (LTFP)](https://www.di.ens.fr/~fbach/ltfp_book.pdf)

### Course Discussion Board

{{< var course.short >}} will use `Piazza` as the course discussion
board. Students are encouraged to direct all questions about course
topics or logistics to Piazza; use of a public anonymous discussion
board allows students to benefit from the insights of their classmates
and allows instructors to answer questions publicly to the benefit 
of all students. 

Students are encouraged to use Piazza's private question feature if
they need to contact the instructor directly. Please only use private
questions for personal inquiries: questions about the technical
substance of the course can and should be asked (pseudonymously) in
the public section of Piazza. 

Piazza login information will be distributed through CUNY Brightspace.

### Communication Resources

Written and oral communication is an important element of this course. 

The [Baruch Writing Center](https://blogs.baruch.cuny.edu/writingcenter/) offers
free support to all Baruch students; students can meet with a professional writing
consultant one-to-one (in person, in NVC 8-185, or online, by video, audio, and
text-based chat) and in group workshops. Writing Center consultants will work
collaboratively with you to deepen your writing and English language skills.
At any step in the process, they’ll help you become a more independent, confident,
and versatile writer.[^0]

Baruch's [Tools for Clear Speech](https://tfcs.baruch.cuny.edu/) program improves
the pronunciation, fluency, and pragmatic abilities of English language learners
and non-native English speakers at Baruch College.  TfCS participants achieve more
effective and intelligible communication, developing skills that empower them
to succeed in their classrooms, careers, and beyond. TfCS offers a range of free
face-to-face and online services with our professional Speech Consultants,
including One-to-One Sessions, small-group Focused Skills Series sessions,
large-group Overview Workshops, interview and career preparation, and weekly
Conversation Hours.

### DataCamp

[DataCamp](https://app.datacamp.com/) generously provides free access to many
of their courses through DataCamp classrooms. I have created a DataCamp 
classroom for this course and assigned lessons that appear to be relevant to
the material covered each week. As a general rule, these lessons will be more
"hands on" and "code oriented" than what we are able to cover in lecture and 
provide a valuable supplement to this course. If there is a DataCamp course 
which is relevant to this course but which I did not assign, please contact me
through Piazza and I will make it available to the class. 

Completion of these DataCamp courses is **not required** and will not be tracked
by the instructor. These are provided to you only as an additional learning
resource. 

A sign-up link will be made available through CUNY Brightspace.

## Course Policies

### Academic Integrity Policy {#aipolicy}

I fully support CUNY’s [Policy on Academic Integrity](https://studentaffairs.baruch.cuny.edu/wp-content/uploads/sites/6/2024/08/CUNY-Academic-Integrity-Policy-2024.pdf), which states, in part:

> Academic dishonesty is prohibited in The City University of New York. 
> Penalties for academic dishonesty include academic sanctions, such as failing 
> or otherwise reduced grades, and/or disciplinary sanctions, including 
> suspension or expulsion.

> Academic integrity is at the core of a college or university education. 
> Faculty assign essays, exams, quizzes, projects, and so on both to extend 
> the learning done in the classroom and as a means of assessing that learning. 
> When students violate the academic integrity policy (i.e., "cheat"), they are 
> committing an act of theft that can cause real harm to themselves and others 
> including, but not limited to, their classmates, their faculty, and the 
> caregivers who may be funding their education. Academic dishonesty confers an
> unfair advantage over others, which undermines educational equity and 
> fairness. Students who cheat place their college’s accreditation and their own
> future prospects in jeopardy.

In this course, expectations for academic integrity for in-class graded activities
are straightforward: no use of unauthorized materials on weekly quizzes or
mid-semester tests. Unless explicitly stated otherwise by the instructor
*in writing*, the only authorized materials allowed during in class assessment
are instructor-provided formula sheets.

The Course Competition is "open peers", "open book", "open internet" but you may
not use **paid** services or **any generative AI** services. You must cite all 
sources used and include an acknowledgement section listing all peers with whom you
collaborated. You do not need to acknowledge the instructor or any Piazza
discussions, but you must acknowledge other faculty members or other Baruch
students who help you complete your reports, even if they are not enrolled in
this course.

Academic sanctions in this class will range from an **F on the Assignment** to
an **F in this Course**. A report of suspected academic dishonesty will be sent
to the Office of the Dean of Students. 

Students are encouraged to contact the instructor with any questions or 
concerns related to matters of academic integrity.


### External Resources Use Policy {#externalresources}

Students are encouraged to make use of any and all external resources, including
generative AI tools, for at home study and for practice problems. 
Students are strongly encouraged to collaborate on weekly practice problems. 
You are ultimately  responsible for the correctness of any submitted materials
- "the AI told me so" is not a valid defense.

The instructor may provide a formula sheet for use during in-class exams. No
alternative resources may be used during these activities unless specifically
pre-authorized by the instructor in writing. 

Students may use online resources, such as blog posts, discussion fora, *etc.* 
for the Course Competition but Generative AI tools are specifically 
**disallowed**. 

> Exception: Coding Assistance Tools, *e.g.*, GitHub CoPilot, may be used for
  the Course Competition. Their usage is limited to *coding*
  your ideas. They may not be used as idea generation tools. 
  
The era of Generative AI is challenging and fast-paced. If you are unsure whether
a tool is allowed in this course, please reach out to the instructor before
using it. In matters of Academic Integrity, it is far better to ask permission
than forgiveness. 


### Late Work Policy

Late work will not be accepted except in extraordinary and unforeseeable
circumstances. Students submitting late work should provide supporting documentation
to the Office of the Dean of Students; ODS will provide the instructor with a letter
authorizing late work submission as appropriate. 

All assignment submission technology used in this course allows
multiple submissions, so students are encouraged to submit early and often
to avoid any technology troubles associated with late submission. 

Note that late work is allowed consistent with specific pre-arranged
course accommodations as noted elsewhere in this document. 

### Communication Policy

Students should use the course discussion board for all course-related
communication. Technical questions, that is, questions either about the course
material or asking for help with an issue specific to your computer, should
always be asked as "Public" and visible to the entire class. Even if you think
an issue is too specific to be of broad interest, it is almost certain that one
of your classmates has a very similar issue and will benefit from your question.
Before posting a new question, students should review previous questions and, if
appropriate, post their question as a follow-up discussion to relevant prior
answers. If your question is large enough to merit a new question, but is similar
to a previous question, please reference the prior post so the instructor knows
that you have already read that question. Failure to do this may result in an
sub-optimal answer (*e.g.*, "go read XYZ"). 

Questions should only be marked as private if they are personal or sensitive, 
*e.g.*, specific questions about grading, request for religious or medical 
accomodation, or discussion of interpersonal conflicts. Questions of potential
broad interest inapporiately marked as private, or sent via email, will be 
closed by the instructor and the student
will be asked to re-post their question publically. 

You should take full advantage of the course discussion board to discuss anything
of interest related to this course: in addition to diving deeper into course
material, please bring in connections to other courses, discussion of news or
cutting-edge research, or general questions about your studies and careers as
data scientists. The most valuable aspects of your education at Baruch are the
connections and community you develop with your classmates and with your faculty.

The instructor will attempt (but not guarantee) to respond within **two business
days** of all student posts.[^onebd] Consequently, if you have a complex issue
requiring significant back-and-forth to resolve, you need to ask for help early. 
In particular, you should submit your mini-projects early and often to 
identify-and hopefully resolve-any technology issues as quickly as possible. 

Be sure to keep your interactions in all course fora helpful, respectful, and
professional. Inappropriate or unpressional postings will be deleted and grade
penalties will be applied for particularly inappropriate interactions. Your
classmates have a wide range of technical background - what is obvious to you
may be difficult for them - so do not be overly curt.

[^onebd]: As a general rule, I do not check the course discussion boards regularly
over weekends or CUNY holidays and you should not expect a rapid response during
these periods. 


#### Unexcused Abscence Policy

Attendance is not required, but lecture recordings will not be provided.
Students are responsible for the content of all sessions missed.


## Course Accomodations

#### Disability Services

It is 
[CUNY policy](https://www.cuny.edu/about/administration/offices/legal-affairs/policies-resources/reasonable-accommodations-and-academic-adjustments/v-accommodations/) 
to provide Accommodations and Academic Adjustments to students with disabilities. 

Any student who has a disability who may need accommodations in this class 
should register as early as possible with [Student Disability Services](https://studentaffairs.baruch.cuny.edu/student-disability-services/) 
(SDS). Your registration with Student Disability Services is confidential, and 
is not recorded on your Baruch Academic Record. SDS can be reached by email at
[disability.services@baruch.cuny.edu](mailto:disability.services@baruch.cuny.edu),
by phone at [646-312-4590](tel:646-312-4590), or in person at NVC 2-272.

Please note that the instructor cannot provide disability-related accommodations
unless requested by SDS.

#### Religious Accomodations

It is 
[CUNY policy](https://www.cuny.edu/about/administration/offices/legal-affairs/policies-resources/reasonable-accommodations-and-academic-adjustments/vi-religious-accommodations/) 
to provide accommodations for students' sincerely held religious beliefs. If a
religious accommodation is requested, please contact the instructor at least two
weeks in advance.


## Additional Baruch and CUNY Benefits

As Baruch students, you have access to a variety of cultural and education
benefits including: 

- Free [New York Times subscription](https://guides.newman.baruch.cuny.edu/newyorktimes)
- Free [Wall Street Journal subscription](https://guides.newman.baruch.cuny.edu/wallstreetjournal)
- Free [Barron's Subscription](https://zicklin.baruch.cuny.edu/current/graduate-advisement-hub/campus-resources/free-subscriptions-for-zicklin-students/) (Zicklin only)
- Free and Discounted [Museum Admissions](https://www.cuny.edu/academics/current-initiatives/cuny-arts/)
- Discounted [Carnegie Hall performances](https://www.carnegiehall.org/Events/Discount-Programs/Student-Insider)
- [GitHub Student Developer Pack](https://education.github.com/pack)
- [Free and Discounted Amazon Prime](https://www.amazon.com/Amazon-Student/b?node=668781011)
- [Apple Computers and Devices](https://www.apple.com/us-edu/store)
- Discounted Spotify & Streaming Services: 
  - [Spotify](https://www.spotify.com/us/student/) (includes Hulu)
  - [Apple Music](https://offers.applemusic.apple/student-offer)
  - [Hulu](https://www.hulu.com/student)
  - [HBO Max](https://www.hbomax.com/student?ref_CC_1)
  - [Peacock](https://www.peacocktv.com/student)
  - [Paramount+](https://www.paramountplus.com/account/signup/edu-offer/)
- [UNiDAYS](https://www.myunidays.com/US/en-US) has many more 

among many others. 

More will posted as I discover them.

## Care Resources for Students[^1]

Take care of yourself. Do your best to maintain a healthy lifestyle this
semester by eating well, exercising, avoiding drugs and alcohol, getting
enough sleep and taking some time to relax. This will help you achieve your
goals and cope with stress. 

All of us benefit from support during times of struggle. You are not alone.
Asking for support sooner rather than later is often helpful. 

This course is intended to be **demanding**, but not **difficult**. If you feel
like you are struggling, please reach out sooner rather than later.
Swimming long-distances in choppy waters builds strength: drowning doesn't.

### Mental Health Resources

If you or anyone you know experiences significant academic stress, difficult
life events, or feelings like anxiety or depression, I strongly encourage you
to seek support.

The [Baruch Counselling Center](https://studentaffairs.baruch.cuny.edu/counseling/)
is here to help. You can visit them in person at 137 E 25th St, 9th floor
or call them at [646-312-2155](tel:646-312-2155) during normal business hours;
you can make an appointment online
[here](https://baruch.az1.qualtrics.com/jfe/form/SV_a4NCaYrV2Sk1cyg). For more
immediate support, please call NYC WELL ([1-888-NYC-WELL](tel:1-888-NYC-WELL) or [1-888-692-9355](tel:1-888-692-9355)). 

Asking for help is often difficult: consider reaching out to a friend,
family, or a member of the faculty you trust for help getting connected to
support that can help. 

If you are worried about a friend or classmate, consider reaching out to the
[Baruch Campus Intervention 
Team](https://studentaffairs.baruch.cuny.edu/campus-intervention-team/).

### Physical Health

[Healthy CUNY](https://www.healthycuny.org/) promotes well-being and a culture
of health in order to foster the academic and life success of all CUNY students.
They can connect you with a variety of [campus-](https://www.healthycuny.org/cuny-health-centers)
and [community](https://www.healthycuny.org/community-health-resources)-based
healthcare providers. 

[Baruch Health Services](https://studentaffairs.baruch.cuny.edu/health/)
provides students with a full range of clinical health services. Call
[646-312-2040](tel:646-312-2040) or email
[StudentHealthCareCenter@baruch.cuny.edu](mailto:StudentHealthCareCenter@baruch.cuny.edu)
to make an appointment.

### Food Security

All CUNY students have access to [CUNY Food
Pantries](https://www.cuny.edu/about/administration/offices/transformation/cuny-cares/food-pantry/)
located throughout the five boroughs, thanks to the [CUNY
CARES](https://www.cuny.edu/about/administration/offices/transformation/cuny-cares/)
program. CUNY CARES is also able to help qualifying students with [SNAP ("Food Stamps")
enrollment](https://www.cuny.edu/current-students/student-affairs/student-services/snap/).

On campus, you can also access the [Bearcat Food Pantry](https://studentaffairs.baruch.cuny.edu/dean-of-students/bearcat-food-pantry/).

### Financial Security
Baruch students experiencing heightened financial stress have access to 
[Student Emergency Grants](https://studentaffairs.baruch.cuny.edu/dean-of-students/emergencyfunds/)
administered through the Office of the Dean of Students. 
Note that funds are also available for students experiencing immigration-related
financial stress.

### Immigration Status

[CUNY Citizenship Now!](https://www.cuny.edu/about/administration/offices/communications-marketing/citizenship-now/)
provides confidential, high-quality immigration law services to all CUNY students. 

Note that Citizenship Now!'s primary Manhattan office is located in the Heights,
not on the Baruch campus and that an appointment is strongly recommended. Call
[646-664-9350](tel:646-664-9350) during standard business hours for more
information or to make an appointment

In situations when more immediate immigration assistance is needed, students
should reach out to the 
[CUNY Immigration Assistance Project (CIAP)](https://www.cuny.edu/about/administration/offices/communications-marketing/immigrationresourcesandinformation/cuny-immigration-assistance-project-ciap/). 

[^0]: Descriptions of Baruch and CUNY resources adapted from program websites.

[^1]: Language adapted from Professor Ryan Tibshirani (UC Berkeley).
