---
title: "{{< var course.short >}} - {{< var course.long >}}"
---

Welcome to the course website for {{< var course.short >}}  - 
{{< var course.long >}} ({{< var course.semester >}})!

{{< var course.short >}} is a survey of Statistical Machine Learning targeted at
students in the [MS in Business
Analytics](https://zicklin.baruch.cuny.edu/academic-programs/graduate/ms/masters-in-business-analytics/), 
[MS in Statistics](https://zicklin.baruch.cuny.edu/academic-programs/graduate/ms/statistics/), 
and [MS in Quantitative Methods](https://zicklin.baruch.cuny.edu/academic-programs/graduate/ms/quantitative-methods-modeling/) 
programs. 

This site hosts the unofficial [Course Syllabus](./syllabus.html), 
[Course Policies](./resources.html), and [Course Learning
Objectives](./objectives.html). Official copies of these documents can be
found on [CUNY Brightspace](https://brightspace.cuny.edu).

This site also hosts descriptions of the [Course Competition](./competition.html)
and [Research Reports (Homework)](./reports.html), as well as selected [Handouts and Additional Notes](notes.html) that will be useful. 

There are quite a few moving parts to this course, so this [key dates file](./key_dates.csv)
or the list of upcoming course activities below may be useful:

```{r echo=FALSE, message=FALSE}
#| echo: false
#| message: false
#| warning: false
library(yaml)
library(glue)
if(file.exists("_variables.yml")){
    variables <- read_yaml("_variables.yml")
} else {
    variables <- read_yaml("https://raw.githubusercontent.com/michaelweylandt/STA9890/refs/heads/main/_variables.yml")
}
course_repo  <- variables$course$repo
course_short <- variables$course$short

readr::read_csv("key_dates.csv") |> 
    dplyr::arrange(Date) |> 
    DT::datatable(options=list(searching=FALSE,
                               paging=TRUE),
                  caption=glue("Upcoming Important Dates for {course_short}"))
```

<script defer>
window.addEventListener("load", function(){
  var filter_date = new Date();
  filter_date.setDate(filter_date.getDate() - 1);
  var filter_string = filter_date.toISOString().split('T')[0]
  $("table").DataTable().rows((idx, data) => data[4] < filter_string).remove().draw();
});
</script>

A CSV file suitable for import into Google Calendar with all assignment deadlines
can be found [here](./key_dates_students_gcal.csv).

Instructor: [Michael Weylandt](https://michael-weylandt.com)
